#!/bin/bash

#PBS -d .
#PBS -l mem=8gb,nodes=1:ppn=1,walltime=12:00:00
#PBS -e error/${sp1}.${sp2}.synNet.err
#PBS -o output/${sp1}.${sp2}.synNet.out

# This script was automatically generated by /cluster/bin/scripts/doBlastzChainNet.pl
# from /hive/data/genomes/hg38/bed/lastzOviAri3.2015-01-21/DEF
# It is to be executed on hgwdev in /hive/data/genomes/hg38/bed/lastzOviAri3.2015-01-21/axtChain .
# It filters the net for synteny and creates syntenic net MAF files for
# multiz. Use this option when the query genome is high-coverage and not
# too distant from the reference.  Suppressed unless -syntenicNet is included.
# This script will fail if any of its commands fail.

module load UCSCtools

netFilter -syn ${sp1}.${sp2}.noClass.net | gzip -c > ${sp1}.${sp2}.syn.net.gz
netToAxt ${sp1}.${sp2}.syn.net.gz ../chain/${sp1}.${sp2}.all.chain \
	 ../genomes/${sp1}.2bit ../genomes/${sp2}.2bit stdout | \
    axtSort stdin stdout | \
    axtToMaf -tPrefix=${sp1}. -qPrefix=${sp2}. stdin \
	     ../genomes/${sp1}.info ../genomes/${sp2}.info stdout | \
    gzip -c > ${sp1}.${sp2}.synNet.maf.gz
